services:
  db:
    image: postgres:16
    container_name: clinicbook-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinicbook
    ports:
      - "5433:5432"
    volumes:
      - clinicbook_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: clinicbook-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clinicbook
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JPA_SHOW_SQL: "true"

volumes:
  clinicbook_data: