spring.application.name=clinic-book

spring.datasource.url=jdbc:postgresql://localhost:5433/clinicbook
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

# application.properties
spring.mvc.format.date=iso
spring.mvc.format.date-time=iso
spring.mvc.format.time=iso